name: cross_file_picker
description: A package that allows you to use the native file explorer to pick single or multiple files/image/video, with extensions filtering support.
version: 1.1.0
homepage: https://github.com/BreX900/cross_file_picker
repository: https://github.com/BreX900/cross_file_picker

scripts:
  publish: flutter pub publish --dry-run

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^6.0.0

  cross_file: ^0.3.3+6

flutter:
